name: L.E.A.F. Technologies Life Sciences
favicon: null
layout_spectrum: 0.6865779771469533
typography_spectrum: 0.8906105489004403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3032256227452308
  lightness: 0.03592309029772878
  saturation: 0.43589900922961533
  rhythmicContrast: 0.17100663669407368
purpose: []
